"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['myhello.py']
DATA_FILES = []
# `tensorflow_core` only exists in 1.15, 2.0 and 2.1
# OPTIONS = {'packages': ['tensorflow', 'tensorflow_core']}
OPTIONS = {'packages': ['tensorflow', 'h5py', 'scipy', 'numpy']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=[
        'py2app', 
        'tensorflow==2.2.0rc', 
        'h5py==2.10.0',
        # 'numpy==1.21.1'
    ],
)

